### PR TITLE
Queries + Sorting + Review 2 Fixes

### LINKED ISSUE #8: Schema validation
Use the registered json-schema to validate instances on most model operations

### LINKED ISSUE #9: Queries: First proposal
Make a first proposal for Queries design API

### LINKED ISSUE #14: Review Round 2  Changes
From #7

- [x] Change `EventCreator` to `EventCodec`, consider fitting names to `Encode/Decode` too
- [x] Delete `SaveOp`
- [x] Second thought to let `EventCodec` be the real reducer, or keep delegating the task from `Model`.
- [x] in-order & safeguard all model state approach for locking strategy of dispatch->reduce
- [x] delete `_ignore` files
- [x] delete ToDos or transform them in real issues to keep track
- [x] Names are off here now... Before -> Previous, After -> Current
- [x] Remove the token registration from `Dispatcher`  to avoid complexity we aren't sure of.

- [ ] Prepare in future PR

### LINKED ISSUE #17: Sorting API

### PR DESCRIPTION
**Pull request by jsign**
New step forward in the store/model implementation.

Changes in this PR are:
* Fixes we discussed about last review (#14) + refactorings
* Queries proposal
* Sorting proposal
* Made `Create`, `Save`, etc operations variadic. I found that cool to avoid even more forcing explicit txns if multiple objects are created, updated, deleted.

Since there's a lot of code again, I think that the most interesting part to review is the Query and Sorting API and implementation. The API is very inspired in badgerhold as the implementation, but was simplified or just done differently for our needs. I kept a copy of their MIT license.

The queries only have `.Eq` operation now, but adding many others is quite trivial since all the building blocks are there. I preferred to move on with more important things. I'll add them as soon as we are surer this is the correct API to avoid work wasting. In the same vein, the code is tested-enough to my needs but should have more coverage.

Before jumping to review, I'd recommend taking a look at [this e2e test](https://github.com/jsign/go-eventstore/blob/5f8bd1808e573fc4768432fa32513998f79b7ead/e2e/books/main.go), which I think is the minimal example that explores all current features of the APIs. This example works, so nothing is mocked here... may help to have the full picture and let play further.

I'll add some comments below to aid in the review. 
Recommended order: 
`e2e/books/main.go`, 
`model.go` (since I moved it all appears new, only take care on my review comments)
`query.go`
`criterion.go`

Fixes #8
Fixes #9
Fixes #14 
Fixes #17

### CODE REVIEW

File: criterion.go [hunk 1]
```diff
@@ -0,0 +1,367 @@
...
+
+import (
+	"fmt"
+	"math/big"
+	"reflect"
+	"strings"
+	"time"
+)
+
+type Criterion struct {
```
Comment (jsign) [inline criterion.go:34]: A `Criterion` is a query operation in a field.
Example `person.Dad.Name == 'Bob'`, would correspond to:
`Criterion { "Dad.Name", Eq, "Bob", x }` where `x` is a chained query which has other criterions.

File: criterion.go [hunk 2]
```diff
@@ -0,0 +1,367 @@
...
+func (c *Criterion) Eq(value interface{}) *Query {
+	c.operation = eq
+	c.value = value
+
+	// First Criterion of a query?
+	if c.query == nil {
+		c.query = &Query{}
+	}
+
+	c.query.ands = append(c.query.ands, c)
```
Comment (jsign) [inline criterion.go:50]: The `Eq` operation (or future operations that will be added), end the construction of a `Criterion` which gets added in the `ands` slice of the current query. This is the mechanics of && operations; a slice of criterions that will be evaluated for `true`.

File: criterion.go [hunk 3]
```diff
@@ -0,0 +1,367 @@
...
+
+	return c.query
+}
+
+func (c *Criterion) compare(testedValue, criterionValue interface{}) (int, error) {
```
Comment (jsign) [inline criterion.go:55]: Here a `Criterion` is tested to a value. Most of the work is done in the `return compare(..)` which basically type-asserts both values, and returns `-1`, `0`, `1`. This result is then interpreted depending on which operation `Criterion` corresponds. So if is an `Eq`, will check for `0`. In future `Le`, `-1`, etc. (see function below `match(..)`)

File: criterion.go [hunk 4]
```diff
@@ -0,0 +1,367 @@
...
+	result, err := c.compare(testValue, c.value)
+	if err != nil {
+		return false, err
+	}
+	switch c.operation {
+	case eq:
+		return result == 0, nil
+	default:
+		panic("invalid operator")
+	}
```
Comment (jsign) [inline criterion.go:84]: Basically what said in the comment above. Adding new operations is adding more cases to the switch statement.

File: criterion.go [hunk 5]
```diff
@@ -0,0 +1,367 @@
...
+}
+
+func traverseFieldPath(value reflect.Value, fieldPath string) (reflect.Value, error) {
```
Comment (jsign) [inline criterion.go:87]: Remember the `Criterion` had the `fieldPath`  to be tested. This basically traverses the object up to that field.

File: criterion.go [hunk 6]
```diff
@@ -0,0 +1,367 @@
...
+	return fmt.Sprintf("%v (%T) cannot be compared with %v (%T)", e.Value, e.Value, e.Other, e.Other)
+}
+
+//Comparer compares a type against the encoded value in the store. The result should be 0 if current==other,
+// -1 if current < other, and +1 if current > other.
+// If a field in a struct doesn't specify a comparer, then the default comparison is used (convert to string and compare)
+// this interface is already handled for standard Go Types as well as more complex ones such as those in time and big
+// an error is returned if the type cannot be compared
+// The concrete type will always be passedin, not a pointer
+type Comparer interface {
```
Comment (jsign) [inline criterion.go:119]: This is an interface that could be implemented by custom types in objects. A pretty neat idea from badgerhold to allow comparing complex types (that can't be type asserted with native Go types)

File: criterion.go [hunk 7]
```diff
@@ -0,0 +1,367 @@
...
+	Compare(other interface{}) (int, error)
+}
+
+func compare(value, other interface{}) (int, error) {
```
Comment (jsign) [inline criterion.go:123]: As said above here there are a bunch of type assertions of Go types to return `-1`, `0`, `1`. 
If it's a `Comparer` it leverages it.
The ultimate fallback is a string conversion to hope for the best.

File: dispatcher.go [hunk 8]
```diff
@@ -50,29 +41,16 @@ func (d *Dispatcher) Store() datastore.TxnDatastore {
 	return d.store
 }
 
-// Register takes a reducer to be invoked with each dispatched event and returns a token for de-registration.
```
Comment (jsign) [inline dispatcher.go:53]: Changes in this file are basically taking out the unregister/registrationtoken we mentioned in past review round.

File: e2e/books/main.go [hunk 9]
```diff
@@ -0,0 +1,164 @@
+package main
```
Comment (jsign) [inline e2e/books/main.go:1]: A simple example to explore what's possible now in the API.

File: e2e/books/main.go [hunk 10]
```diff
@@ -0,0 +1,164 @@
...
+			Title:  "Title1",
+			Author: "Author1",
+			Meta:   BookStats{TotalReads: 100, Rating: 3.2},
+		}
+		book2 := &Book{
+			Title:  "Title2",
+			Author: "Author1",
+			Meta:   BookStats{TotalReads: 150, Rating: 4.1},
+		}
+		checkErr(model.Create(book1, book2)) // Note you can create multiple books at the same time (variadic)
```
Comment (jsign) [inline e2e/books/main.go:41]: An example of the variadic change I made to the api.
Compared to what was possible before, this would mean making to `model.Create(..)` without transactional guarantees between them. Or opening an explicit `WriteTxn(..)` to make it transactional. Now this change do the latter for you.

File: e2e/books/main.go [hunk 11]
```diff
@@ -0,0 +1,164 @@
...
+			Author: "Author2",
+			Meta:   BookStats{TotalReads: 500, Rating: 4.9},
+		}
+		checkErr(model.Create(book3))
+	}
+
+	// Query all the books
+	{
+		var books []*Book
+		err := model.Find(&books, &es.Query{})
```
Comment (jsign) [inline e2e/books/main.go:55]: Could be `nil` also instead of `&Query{}`

File: e2e/books/main.go [hunk 12]
```diff
@@ -0,0 +1,164 @@
...
+		checkErr(err)
+		if len(books) != 2 {
+			panic("Author1 should have two books")
+		}
+	}
+
+	// Query with nested condition
+	{
+		var books []*Book
+		err := model.Find(&books, es.Where("Meta.TotalReads").Eq(100))
```
Comment (jsign) [inline e2e/books/main.go:75]: An example of a nested field query.

File: e2e/books/main.go [hunk 13]
```diff
@@ -0,0 +1,164 @@
...
+		checkErr(err)
+		if len(books) != 1 {
+			panic("There should be one book with 100 total reads")
+		}
+	}
+
+	// Query book by two conditions
+	{
+		var books []*Book
+		err := model.Find(&books, es.Where("Author").Eq("Author1").And("Title").Eq("Title2"))
```
Comment (jsign) [inline e2e/books/main.go:85]: An example of chained `Criterion`s.

File: e2e/books/main.go [hunk 14]
```diff
@@ -0,0 +1,164 @@
...
+		checkErr(err)
+		if len(books) != 1 {
+			panic("Author1 should have only one book with Title2")
+		}
+	}
+
+	// Query book by OR condition
+	{
+		var books []*Book
+		err := model.Find(&books, es.Where("Author").Eq("Author1").Or(es.Where("Author").Eq("Author2")))
```
Comment (jsign) [inline e2e/books/main.go:95]: An example how an `Or` feels.

File: e2e/books/main.go [hunk 15]
```diff
@@ -0,0 +1,164 @@
...
+		if len(books) != 3 {
+			panic("Author1 & Author2 have should have 3 books in total")
+		}
+	}
+
+	// Sorted query
+	{
+		var books []*Book
+		// Ascending
+		err := model.Find(&books, es.Where("Author").Eq("Author1").OrderBy("Meta.TotalReads"))
```
Comment (jsign) [inline e2e/books/main.go:106]: An example of `OrderBy` with nested field.

File: e2e/books/main.go [hunk 16]
```diff
@@ -0,0 +1,164 @@
...
+		checkErr(err)
+		if books[0].Meta.TotalReads != 100 || books[1].Meta.TotalReads != 150 {
+			panic("books aren't ordered asc correctly")
+		}
+		// Descending
+		err = model.Find(&books, es.Where("Author").Eq("Author1").OrderByDesc("Meta.TotalReads"))
```
Comment (jsign) [inline e2e/books/main.go:112]: Order in another direction.

File: e2e/books/main.go [hunk 17]
```diff
@@ -0,0 +1,164 @@
...
+		checkErr(err)
+		if books[0].Meta.TotalReads != 150 || books[1].Meta.TotalReads != 100 {
+			panic("books aren't ordered desc correctly")
+		}
+	}
+
+	// Query, Update, and Save
```
Comment (jsign) [inline e2e/books/main.go:119]: A little more complex example to check that all things are coherent.

File: e2e/books/main.go [hunk 18]
```diff
@@ -0,0 +1,164 @@
...
+		err = model.Find(&books, es.Where("Title").Eq("ModifiedTitle"))
+		checkErr(err)
+		if len(books) != 0 {
+			panic("Book with ModifiedTitle shouldn't exist")
+		}
+	}
+
+	// ToDo: Indexes for improved perf
+	// ToDo: Self-referencing conditionals?
+	// ToDo: Multi-sort criteria?
```
Comment (jsign) [inline e2e/books/main.go:151]: Future. I think the index creation api should be quite simple.
Levereaging existing indexes in queries or in sorting feels reasonable, but that's a future discussion/proposal!.

File: model.go [hunk 19]
```diff
@@ -0,0 +1,300 @@
...
+	return m
+}
+
+func (m *Model) ReadTxn(f func(txn *Txn) error) error {
+	return m.store.readTxn(m, f)
+}
+
+func (m *Model) WriteTxn(f func(txn *Txn) error) error {
+	return m.store.writeTxn(m, f)
+}
```
Comment (jsign) [inline model.go:60]: As discussed in last review.
Txns scope was moved to the `Store`. This is the reasonable _fix_ to make them as much safe for the current user as possible. No transaction can interfere with other models in the store, or by remote events dispatched.

File: model.go [hunk 20]
```diff
@@ -0,0 +1,300 @@
...
+		log.Debugf("ignoring event from uninteresting type")
+		return nil
+	}
+
+	return m.eventcodec.Reduce(event, m.datastore, m.dsKey)
+}
+
+func (m *Model) validInstance(v interface{}) (bool, error) {
+	vLoader := gojsonschema.NewGoLoader(v)
+	r, err := gojsonschema.Validate(m.schemaLoader, vLoader)
```
Comment (jsign) [inline model.go:112]: New thing here for schema validation when instances are created or updated.

File: model.go [hunk 21]
```diff
@@ -0,0 +1,300 @@
...
+
+	actions []core.Action
+}
+
+func (t *Txn) Create(new ...interface{}) error {
+	for i := range new {
+		if t.readonly {
+			return ErrReadonlyTx
+		}
+		valid, err := t.model.validInstance(new[i])
```
Comment (jsign) [inline model.go:134]: Here the instance is validated against schema.

File: query.go [hunk 22]
```diff
@@ -0,0 +1,164 @@
...
+)
+
+type Query struct {
+	ands []*Criterion
+	ors  []*Query
+	sort struct {
+		field string
+		desc  bool
+	}
+}
```
Comment (jsign) [inline query.go:31]: Conceptually a `Query` is a chain of `ands` `Criterion`s, and a set of `ors` other `Query`s.
To evaluate a `Query`, all `ands` should be `true`. If that isn't the case, at least one `ors` should evaluate `true`.
The `sort` field is used afterwards to sort the result.

File: query.go [hunk 23]
```diff
@@ -0,0 +1,164 @@
...
+
+func Where(field string) *Criterion {
+	return &Criterion{
+		fieldPath: field,
+	}
+}
```
Comment (jsign) [inline query.go:37]: `Where` *starts* building a `Criterion`, which stores the field path to be evaluated. I'd recommend jumping to `criterion.go` and see the `Eq(..)` function, which completes the `Criterion` creation.

File: query.go [hunk 24]
```diff
@@ -0,0 +1,164 @@
...
+
+func (q *Query) And(field string) *Criterion {
+	return &Criterion{
+		fieldPath: field,
+		query:     q,
+	}
+}
```
Comment (jsign) [inline query.go:44]: `And` is similar to `Where`, but is what's used when you're already chaining to an existing `Query`.

File: query.go [hunk 25]
```diff
@@ -0,0 +1,164 @@
...
+
+func (q *Query) Or(orQuery *Query) *Query {
```
Comment (jsign) [inline query.go:46]: Chains an `Or` condition to a current query.

File: query.go [hunk 26]
```diff
@@ -0,0 +1,164 @@
...
+	q.sort.field = field
+	q.sort.desc = false
+	return q
+}
+
+func (q *Query) OrderByDesc(field string) *Query {
+	q.sort.field = field
+	q.sort.desc = true
+	return q
+}
```
Comment (jsign) [inline query.go:61]: To set orders in the current `Query`. Will be taken into consideration at the end of evaluation for ordering.
If is called multiple times, the last time will be considered. We could accept variadic in the parameters to field by multiple fields... this is a simplification compared to badgerhold which does it.

File: query.go [hunk 27]
```diff
@@ -0,0 +1,164 @@
...
+
+func (q *Query) match(v reflect.Value) (bool, error) {
```
Comment (jsign) [inline query.go:63]: Given an object, it checks if it satisfies the `Query`.

File: query.go [hunk 28]
```diff
@@ -0,0 +1,164 @@
...
+		ok, err := criterion.match(fieldForMatch)
+		if err != nil {
+			return false, err
+		}
+		andOk = andOk && ok
+		if !andOk {
+			break
+		}
+	}
+	if andOk {
```
Comment (jsign) [inline query.go:83]: `ands` all evaluated true?, if yes, we're done. (Not `ors` are evaluated / short-circuit).

File: query.go [hunk 29]
```diff
@@ -0,0 +1,164 @@
...
+		return true, nil
+	}
+
+	for _, q := range q.ors {
```
Comment (jsign) [inline query.go:87]: `ands` failed. Return true on the first `ors` that evaluates true.

File: query.go [hunk 30]
```diff
@@ -0,0 +1,164 @@
...
+		if ok {
+			return true, nil
+		}
+	}
+
+	return false, nil
+}
+
+func (t *Txn) Find(res interface{}, q *Query) error {
+	// ToDo: context cancellation? (to call dsr.Close())
```
Comment (jsign) [inline query.go:101]: An idea that might be interesting to consider: cancellable queries.

File: query.go [hunk 31]
```diff
@@ -0,0 +1,164 @@
...
+	if valRes.Kind() != reflect.Ptr || valRes.Elem().Kind() != reflect.Slice {
+		panic("result should be a slice")
+	}
+	if q == nil {
+		q = &Query{}
+	}
+	dsq := dsquery.Query{
+		Prefix: t.model.dsKey.String(),
+	}
+	dsr, err := t.model.datastore.Query(dsq)
```
Comment (jsign) [inline query.go:112]: The idea here is making a simple implementation to move forward.
It does a query to the underlying datastore.
It starts iterating the results.
Checks the `Query` against them. If true, add to an `unsorted` slice result.
After finishing, check if the query involves sorting. If that's the case, sort, and return.

When we'll have indexes, they could be used to avoid the full datastore query, and start with the indexed field (if has any condition in the query, or it is a sorting field). Some work here, but it seems doable.

Edit: A lot of reflect magic here, just what's necessary to make things work.

File: store.go [hunk 32]
```diff
@@ -0,0 +1,104 @@
...
+	s.lock.Lock()
+	defer s.lock.Unlock()
+
+	txn := &Txn{model: m}
+	defer txn.Discard()
+	if err := f(txn); err != nil {
+		return err
+	}
+	return txn.Commit()
+}
```
Comment (jsign) [inline store.go:82]: Part of the change to make txn `Store`-wise.

File: store.go [hunk 33]
```diff
@@ -0,0 +1,104 @@
...
+
+// Dispatch applies external events to the store. This function guarantee
+// no interference with registered model states, and viceversa.
+func (s *Store) Dispatch(e core.Event) {
+	s.lock.Lock()
+	defer s.lock.Unlock()
+	s.dispatcher.Dispatch(e)
+}
```
Comment (jsign) [inline store.go:90]: A consequence of making txn `Store`-wise (so remote events don't interfiere with local txns), make sense.

In this moment is where it seems that the `Store` is the real aggregate of the whole mechanics. The component that will `Dispatch` remote events should call `Dispatch` from `Store`s (if there're more than one in an app, which I'm not sure makes sense). Then this `store.Dispatch(..)` will gain exclusive write-lock (to not interfere with all the models state of the `Store`), and dispatch to internal dispatcher which will yield the event to all model reducers.

This seems to indicate that the `Dispatcher` shouldn't be public, but internally owned by the `Store`.
I think that when we connect things with remote events some things will start to confirm and we can take care of what visibility should have each thing. Just mentioning all these to help with the mental model of how things fit now.

File: criterion.go [hunk 34]
```diff
@@ -0,0 +1,367 @@
...
+
+	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
+	SOFTWARE.
+*/
+// Code has multiple changes compared to original, but corresponds proper mentioning.
```
Comment (jsign) [inline criterion.go:23]: Most code taken from badgerhold is in this file, despite many things were changed. I appended the MIT licence to be tidy in copyrights.

**Review by jsign — COMMENTED** [review]
I hope comments help!

File: core/event.go [hunk 35]
```diff
@@ -57,3 +62,32 @@ func (n *nullEvent) Type() string {
...
+// Action is a operation done in the model
+type Action struct {
+	// Type of the action
+	Type ActionType
+	// EntityID of the instance in action
+	EntityID EntityID
+	// EntityType of the instance in action
+	EntityType string
+	// Previous is the instance before the action
+	Previous interface{}
```
Comment (sanderpick) [inline core/event.go:83]: What's the function of previous?

File: criterion.go (hunk 1 above)
Comment (sanderpick) [reply criterion.go:34]: Very cool

File: e2e/books/main.go (hunk 10 above)
Comment (sanderpick) [reply e2e/books/main.go:41]: Neat!

File: query.go (hunk 26 above)
Comment (sanderpick) [reply query.go:61]: Slick

File: store.go (hunk 33 above)
Comment (sanderpick) [reply store.go:90]: From a user perspective, I like the idea of just exposing a Store. Probably the store will have to have some reference to a Threadservice, which can be used to inject network events. Lots of open questions, like, how does a model relate to a thread? One per model, one per instance, etc.?

**Review by sanderpick — APPROVED** [review]
🔥 Another big one! 🔥

It's really cool to see this coming to life. I spent some time going through and don't have any nitty comments, but there's a lot of code 😅. The query syntax seems pretty nice and it's good to have badgerhold as a kind of end user UX validation.

Out of curiosity, did you look at https://github.com/tidwall/buntdb for inspiration?

File: store.go (hunk 33 above)
Comment (jsign) [reply store.go:90]: Yeah, agree on those questions. Let's hope that moving forward will give some answers.

**Comment by sanderpick** [comment]
Oh, I forgot to mention: At some point, it would be fun to play with the idea of reactive style queries where you get matches over a channel as they come in.

File: core/event.go (hunk 35 above)
Comment (jsign) [reply core/event.go:83]: `Previous` is needed by the `EventCreator`, for creating deltas of state.
Example: the current json-patcher uses `Previous` and `Current` in update actions to calculate the corresponding json-patch which will be the payload of the event that generates.

Now that you're mentioning this, I think can be avoided, since the `EventCreator` has access to the underlying datastore and can get the "previous" value with the `EntityID` also stored in the `Action`. (since the datastore is still unchanged at this point). Maybe you were thinking that.

Comment (sanderpick) [reply core/event.go:83]: Ah, ok. Makes sense. I wasn't thinking that... just needed a refresher

**Comment by jsign** [comment]
> fire Another big one! fire
> 
> It's really cool to see this coming to life. I spent some time going through and don't have any nitty comments, but there's a lot of code sweat_smile. The query syntax seems pretty nice and it's good to have badgerhold as a kind of end user UX validation.
> 
> Out of curiosity, did you look at https://github.com/tidwall/buntdb for inspiration?

Yes, I remember taking a look at it. I wasn't convinced much by the low-level feeling of using attribute paths as keys (like `user:dad:name`, `user:name`, to represent a `user` object). Might take a look again when we define the indexing API though.

**Comment by jsign** [comment]
> Oh, I forgot to mention: At some point, it would be fun to play with the idea of reactive style queries where you get matches over a channel as they come in.

Yeah, totally doable. Similarly, maybe having _projections_ which is updated data on top of the defined model... can be like views, or aggregations or similar things.
A lot to play leveraging the event-based way that makes state changes in the model.

**Comment by jsign** [comment]
@sanderpick , do you feel that the e2e example has a somewhat good feeling?

If that's the case I'll merge and give move forward adding the further operations for queries and leaving test-coverage to a decent point. We can also wait a bit to see what others think about it.

**Comment by sanderpick** [comment]
Makes sense. I forgot about the low level feel of bunt. Agreed it could be useful for indexing inspiration. 

Re/ e2e example, yeah, I like it. Feels like a huge step in the right direction. Fine by me to merge.
